# docker-compose config
# docker-compose -up
version: '3'  # 指定版本号
services:     # 开始编写服务
  webapp:     # 镜像名称
    build:    # 使用build指令 编写执行docker build程序
      context: .         # 指定Dockerfile所在文件夹
      dockerfile: Dockerfile  # 指定Dockerfile文件名
      args:                   # 设定构建参数
        PATH: /app/www
    environment:
        ALPINE_VERSION: ${ALPINE_VERSION}