<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

namespace GPBMetadata;

class Game
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa1010a0a67616d652e70726f746f12046772706322200a0c48656c6c6f" .
            "5265717565737412100a086772656574696e67180120012809221e0a0d48" .
            "656c6c6f526573706f6e7365120d0a057265706c7918012001280932430a" .
            "0c48656c6c6f5365727669636512330a0853617948656c6c6f12122e6772" .
            "70632e48656c6c6f526571756573741a132e677270632e48656c6c6f5265" .
            "73706f6e7365620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

